//! Embeds the vendored RBS signatures into the binary.
//!
//! `workspace::rbs` prefers an `rbs` gem found on disk. This is the rung below that: on a
//! machine with no Ruby installed there is no other source of built-in signatures, and a server
//! whose whole claim is "works without Ruby" cannot have `String` disappear there.
//!
//! The generated file is a list of `(relative path, contents)`, one `include_str!` per
//! signature. Packing them into a single blob with a hand-rolled index would save the compiler
//! some work and cost a format nobody can read; `include_str!` also fails the build loudly if a
//! vendored file stops being UTF-8, which is the only validation this stage can usefully do.

use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("set by cargo"));
    let vendor = manifest.join("vendor").join("rbs");
    let out = PathBuf::from(env::var("OUT_DIR").expect("set by cargo")).join("rbs_embedded.rs");

    let version_file = vendor.join("VERSION");
    println!("cargo:rerun-if-changed={}", version_file.display());
    let version = fs::read_to_string(&version_file)
        .unwrap_or_else(|error| panic!("reading {}: {error}", version_file.display()))
        .trim()
        .to_owned();
    assert!(!version.is_empty(), "vendor/rbs/VERSION is empty");

    let mut files = Vec::new();
    collect(&vendor, &vendor, &mut files);
    // Sorted so the generated file is stable: an unsorted `read_dir` order would make every
    // rebuild on a different machine produce a different binary.
    files.sort();
    assert!(
        !files.is_empty(),
        "no .rbs files under {} — see its README for how to refresh them",
        vendor.display()
    );

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs from vendor/rbs. Do not edit.\n");
    generated.push_str(&format!("pub const VERSION: &str = {version:?};\n"));
    generated.push_str("pub static FILES: &[(&str, &str)] = &[\n");
    for relative in &files {
        let absolute = vendor.join(relative);
        println!("cargo:rerun-if-changed={}", absolute.display());
        // Forward slashes in the key on every platform: it becomes a path component below the
        // extraction directory, and a literal backslash in a file name is not what Windows
        // wants either.
        let key = relative.to_string_lossy().replace('\\', "/");
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            key,
            absolute.to_string_lossy()
        ));
    }
    generated.push_str("];\n");

    fs::write(&out, generated).unwrap_or_else(|error| panic!("writing {}: {error}", out.display()));
}

/// Every `.rbs` file under `directory`, as a path relative to `base`.
fn collect(base: &Path, directory: &Path, found: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(error) => panic!("reading {}: {error}", directory.display()),
    };
    for entry in entries {
        let path = entry.expect("readable directory entry").path();
        if path.is_dir() {
            collect(base, &path, found);
        } else if path.extension().is_some_and(|extension| extension == "rbs") {
            found.push(
                path.strip_prefix(base)
                    .expect("walked from base")
                    .to_path_buf(),
            );
        }
    }
}
