//! What `--licenses` prints.
//!
//! # Why this exists rather than a file beside the binary
//!
//! The binary embeds Ruby's own RBS signatures (see [`crate::workspace::rbs`]), which are
//! BSD-2-Clause material. That licence requires its copyright notice, conditions and disclaimer
//! to be reproduced in the materials accompanying a distribution in *binary* form — and the
//! obligation belongs to the artifact, not to the repository it was built from. A VSIX can carry
//! a licence file; a bare binary attached to a release, rehosted, or installed with
//! `cargo install` has no accompanying materials at all.
//!
//! Carrying the notice *inside* the binary is the only arrangement that cannot come apart from
//! it. Every other option — an archive, a second release asset, a line in the release notes — has
//! to be remembered again for each new way of shipping.
//!
//! # Why three files rather than one
//!
//! Each is a different document with a different author. `LICENSE.txt` is ya-lsp's own terms and
//! nothing else, which is what lets GitHub and any other licence detector recognise it as MIT;
//! `NOTICE.txt` is the rbs material; `THIRD-PARTY-NOTICES.txt` is generated.
//!
//! The texts are `include_str!`d rather than produced by `build.rs`: rustc tracks an
//! `include_str!` as a dependency, so editing any of these files rebuilds, and the licence that
//! ships cannot drift from the licence in the tree.
//!
//! # Why the crate notices are committed rather than generated at build time
//!
//! `THIRD-PARTY-NOTICES.txt` is produced by `cargo about` from the dependency graph. Running that
//! from `build.rs` would put a tool nobody has on the critical path of `cargo build` and
//! `cargo install`, so it is generated by hand, committed, and checked in CI — the same trade a
//! lockfile makes. `cargo about generate about.hbs -o THIRD-PARTY-NOTICES.txt` regenerates it,
//! and CI fails if the result differs from what is committed.

/// ya-lsp's own terms. MIT, and only MIT — see the module docs.
const OWN: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/LICENSE.txt"));

/// The rbs material: the vendored signatures and the C parser crates, with both of rbs's
/// licences reproduced in full.
///
/// This is the only place the copyright holder is named. `cargo about` cannot name them —
/// neither `ruby-rbs` nor `ruby-rbs-sys` publishes a licence file for it to harvest, so the
/// generated notice falls back to the SPDX template and its unfilled `<year> <owner>` line.
const NOTICE: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/NOTICE.txt"));

/// Every crate linked into this binary, generated by `cargo about`.
const CRATES: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/THIRD-PARTY-NOTICES.txt"
));

/// Everything this binary is obliged to reproduce, as one document.
#[must_use]
pub fn text() -> String {
    format!(
        "\
ya-lsp {}
===============================================================================

{}

{}

{}",
        env!("CARGO_PKG_VERSION"),
        OWN.trim_end(),
        NOTICE.trim_end(),
        CRATES.trim_end(),
    )
}

#[cfg_attr(coverage_nightly, coverage(off))]
#[cfg(test)]
mod tests {
    use super::*;

    /// The licences as their upstream ships them, which is what `NOTICE.txt` has to reproduce.
    const BSDL: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/vendor/rbs/BSDL"));
    const RUBY: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/vendor/rbs/COPYING"));

    #[test]
    fn every_obligation_is_reproduced() {
        let text = text();
        // The BSD-2-Clause notice, its conditions, and its disclaimer: the three things the
        // licence names, checked as three separate phrases so dropping one is not silent.
        for phrase in [
            "Copyright (C) 2019 Soutaro Matsumoto",
            "Redistributions in binary form must reproduce the above copyright",
            "THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS",
        ] {
            assert!(text.contains(phrase), "missing from --licenses: {phrase:?}");
        }
        // Our own, and the other half of rbs's dual licence.
        assert!(text.contains("The MIT License (MIT)"));
        assert!(text.contains("Copyright (c) 2026 Artem Shevchenko"));
        assert!(text.contains("rbs is copyrighted free software"));
    }

    /// `NOTICE.txt` is hand-written, and the licences inside it are copies of files that a
    /// `vendor/rbs` bump can rewrite. A copy that has drifted is a licence nobody granted.
    #[test]
    fn the_notice_reproduces_both_licences_verbatim() {
        for (name, licence) in [("BSDL", BSDL), ("COPYING", RUBY)] {
            assert!(
                NOTICE.contains(licence.trim_end()),
                "NOTICE.txt no longer reproduces vendor/rbs/{name} verbatim; \
                 re-assemble it from the file"
            );
        }
    }

    /// The version is the one thing in the notice that is not a fixed string, and it is what
    /// tells a reader which signatures they actually have.
    #[test]
    fn the_notice_names_the_vendored_version() {
        let version = crate::workspace::rbs::vendored_version();
        assert!(
            NOTICE.contains(version),
            "NOTICE.txt does not name rbs {version}; it was bumped without updating the notice"
        );
    }

    /// `LICENSE.txt` carried the rbs notice appended after a `---` until it was split out, and
    /// appending to it again is the obvious way to undo that. It costs the MIT detection that
    /// GitHub and every other licence scanner do by matching the file against a template.
    #[test]
    fn the_licence_file_is_only_the_licence() {
        assert!(
            !OWN.contains("---"),
            "LICENSE.txt has something appended to it"
        );
        assert!(
            !OWN.contains("Soutaro"),
            "the rbs notice is back in LICENSE.txt"
        );
        assert!(OWN.trim_end().ends_with("THE SOFTWARE."));
    }

    #[test]
    fn the_crates_linked_into_the_binary_are_covered_too() {
        let text = text();
        // The generated section, and the two entries that motivated generating it: rbs's C
        // parser is compiled in by `ruby-rbs-sys` and is BSD-2-Clause, which the hand-written
        // notice above never covered because it is about the signature files.
        assert!(text.contains("Third-party notices: crates linked into this binary"));
        for crate_name in ["ruby-rbs-sys", "ruby-prism", "rubydex", "lsp-types"] {
            assert!(text.contains(crate_name), "not covered: {crate_name}");
        }
        // Per-crate copyright lines, not one generic licence body: MIT asks for *the above*
        // copyright notice, which is each crate's own.
        let holders = [
            "Alex Crichton",
            "Andrew Gallant",
            "The Rust Project Developers",
        ];
        for holder in holders {
            assert!(text.contains(holder), "no copyright line for {holder}");
        }
    }

    #[test]
    fn nothing_is_left_as_a_pointer_to_a_file() {
        // The whole point is that the binary is self-contained. A notice that says "see
        // vendor/rbs/BSDL" is useless to somebody holding only the binary.
        let text = text();
        assert!(
            !text.contains("vendor/rbs/BSDL") && !text.contains("vendor/rbs/COPYING"),
            "--licenses points at files instead of reproducing them"
        );
    }
}
